-- Ideas system: interactions, analysis, weekly digest
-- Run: psql $DATABASE_URL -f backend/migrations/005_ideas_system.sql

-- User interactions with ideas (dismiss, save, unlock)
CREATE TABLE IF NOT EXISTS user_idea_interactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  idea_id UUID NOT NULL REFERENCES discovered_ideas(id) ON DELETE CASCADE,
  action VARCHAR(20) NOT NULL CHECK (action IN ('dismiss', 'save', 'unlock')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, idea_id, action)
);

CREATE INDEX IF NOT EXISTS idx_uii_user ON user_idea_interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_uii_idea ON user_idea_interactions(idea_id);

-- Idea analysis cache (generated by LLM, cached to avoid re-generation)
CREATE TABLE IF NOT EXISTS idea_analyses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  idea_id UUID NOT NULL REFERENCES discovered_ideas(id) ON DELETE CASCADE UNIQUE,
  why_it_works TEXT NOT NULL,        -- "Por qué creemos que funciona"
  market_size TEXT,                   -- Tamaño estimado del mercado
  competition_level VARCHAR(20),      -- baja/media/alta
  time_to_mvp TEXT,                   -- "2-4 semanas"
  monetization_strategy TEXT,         -- Cómo monetizar
  risk_factors TEXT,                  -- Riesgos principales
  metrics JSONB,                      -- { searches_monthly, growth_rate, engagement, etc }
  generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add analysis_generated flag to discovered_ideas
ALTER TABLE discovered_ideas ADD COLUMN IF NOT EXISTS analysis_generated BOOLEAN DEFAULT false;

-- Add batch_id to track weekly batches
ALTER TABLE discovered_ideas ADD COLUMN IF NOT EXISTS batch_id VARCHAR(10);

-- Weekly digest tracking (avoid sending duplicate emails)
CREATE TABLE IF NOT EXISTS weekly_digest_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  batch_id VARCHAR(10) NOT NULL,      -- e.g. "2026-W10"
  sent_at TIMESTAMPTZ DEFAULT NOW(),
  ideas_count INTEGER DEFAULT 0,
  UNIQUE(user_id, batch_id)
);
