-- Migration 018: Marketing content pieces + Ad campaigns
-- Supports Gamma API integration for presentations/social/docs
-- and Ads Strategist agent campaigns

-- ═══ Content Pieces (Gamma-generated + manual) ═══
CREATE TABLE IF NOT EXISTS content_pieces (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  
  -- Content type and format
  type TEXT NOT NULL DEFAULT 'social_post', -- social_post, presentation, document, carousel, webpage
  format TEXT, -- linkedin_post, instagram_carousel, twitter_thread, pitch_deck, proposal, blog_post
  title TEXT,
  body TEXT, -- Raw text content or prompt used
  
  -- Gamma integration
  gamma_generation_id TEXT,
  gamma_url TEXT, -- Link to the generated Gamma
  gamma_status TEXT, -- pending, completed, failed
  gamma_credits_used INTEGER DEFAULT 0,
  gamma_export_url TEXT, -- PDF/PPTX export link
  
  -- Publishing
  status TEXT NOT NULL DEFAULT 'draft', -- draft, generating, ready, scheduled, posted, failed
  platform TEXT, -- linkedin, twitter, instagram, email, internal
  scheduled_for TIMESTAMPTZ,
  posted_at TIMESTAMPTZ,
  post_url TEXT, -- URL of the live post
  
  -- Engagement tracking
  engagement_views INTEGER DEFAULT 0,
  engagement_likes INTEGER DEFAULT 0,
  engagement_comments INTEGER DEFAULT 0,
  engagement_shares INTEGER DEFAULT 0,
  engagement_clicks INTEGER DEFAULT 0,
  
  -- Metadata
  created_by TEXT NOT NULL DEFAULT 'agent', -- agent, user
  agent_tag TEXT, -- marketing, twitter, email
  tags TEXT[], -- arbitrary tags
  metadata JSONB DEFAULT '{}',
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_content_pieces_company ON content_pieces(company_id);
CREATE INDEX IF NOT EXISTS idx_content_pieces_status ON content_pieces(status);
CREATE INDEX IF NOT EXISTS idx_content_pieces_type ON content_pieces(type);
CREATE INDEX IF NOT EXISTS idx_content_pieces_gamma ON content_pieces(gamma_generation_id);

-- ═══ Ad Campaigns (Strategist-generated) ═══
CREATE TABLE IF NOT EXISTS ad_campaigns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  
  -- Campaign info
  name TEXT NOT NULL,
  objective TEXT, -- awareness, traffic, leads, conversions, engagement
  platform TEXT NOT NULL, -- google_ads, meta_ads, linkedin_ads, tiktok_ads, general
  status TEXT NOT NULL DEFAULT 'draft', -- draft, ready, active, paused, completed
  
  -- Strategy
  target_audience JSONB DEFAULT '{}', -- demographics, interests, pain points
  keywords TEXT[], -- for search ads
  negative_keywords TEXT[],
  
  -- Budget
  suggested_daily_budget NUMERIC(10,2),
  suggested_monthly_budget NUMERIC(10,2),
  actual_spend NUMERIC(10,2) DEFAULT 0,
  currency TEXT DEFAULT 'EUR',
  
  -- Ad creatives (generated by agent)
  ad_copies JSONB DEFAULT '[]', -- [{headline, description, cta, variant}]
  creative_urls TEXT[], -- Gamma-generated creative URLs
  landing_page_url TEXT,
  
  -- Performance (user-entered or synced)
  impressions INTEGER DEFAULT 0,
  clicks INTEGER DEFAULT 0,
  conversions INTEGER DEFAULT 0,
  cost_per_click NUMERIC(10,4),
  cost_per_conversion NUMERIC(10,4),
  roas NUMERIC(10,2), -- Return on ad spend
  
  -- Metadata
  created_by TEXT NOT NULL DEFAULT 'agent',
  notes TEXT,
  metadata JSONB DEFAULT '{}',
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ad_campaigns_company ON ad_campaigns(company_id);
CREATE INDEX IF NOT EXISTS idx_ad_campaigns_status ON ad_campaigns(status);
CREATE INDEX IF NOT EXISTS idx_ad_campaigns_platform ON ad_campaigns(platform);

-- ═══ Gamma API usage tracking ═══
CREATE TABLE IF NOT EXISTS gamma_usage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  generation_id TEXT NOT NULL,
  content_piece_id UUID REFERENCES content_pieces(id),
  format TEXT, -- presentation, document, social, webpage
  credits_deducted INTEGER DEFAULT 0,
  status TEXT DEFAULT 'pending', -- pending, completed, failed
  gamma_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gamma_usage_company ON gamma_usage(company_id);
