-- Migración 007: Seed inicial de ideas curadas para el mercado hispano
-- Sólo inserta si discovered_ideas está vacía (idempotente)
-- 25 ideas de negocio validadas con evidencia real de demanda

-- Asegurar columnas adicionales
ALTER TABLE discovered_ideas ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE discovered_ideas ADD COLUMN IF NOT EXISTS analysis_generated BOOLEAN DEFAULT false;
ALTER TABLE discovered_ideas ADD COLUMN IF NOT EXISTS times_launched INTEGER DEFAULT 0;
ALTER TABLE discovered_ideas ADD COLUMN IF NOT EXISTS batch_id VARCHAR(10);

-- Insertar sólo si la tabla está vacía (o no tiene ideas activas)
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM discovered_ideas WHERE is_active = true) = 0 THEN

    INSERT INTO discovered_ideas (
      id, title, problem, target_audience, evidence,
      source, category, difficulty, potential_revenue, score,
      status, is_active, discovered_at, created_at
    ) VALUES
    (gen_random_uuid(), 'Facturación Automática con IA para Autónomos', 'Los autónomos en España y LATAM pierden horas al mes gestionando facturas. Los programas actuales son caros o difíciles. Las facturas recurrentes se olvidan y el IRPF se complica.', 'Autónomos, freelancers, pequeños negocios en España y LATAM', '200+ posts en r/autónomos, 80+ hilos en foros fiscales España, demanda masiva en Quora Hispano', 'reddit', 'saas', 'medium', '2.000€-8.000€/mes', 91, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Asistente IA para Atención al Cliente en WhatsApp', 'Las PYMEs reciben mensajes de WhatsApp que no pueden gestionar. Contratan personas solo para responder. Las herramientas de chatbot genéricas no entienden el español coloquial.', 'PYMEs con tiendas físicas, ecommerce pequeño, restaurantes', '150+ menciones en grupos de WhatsApp Business, 60+ posts en LinkedIn de dueños de negocio', 'twitter', 'saas', 'medium', '3.000€-12.000€/mes', 89, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Academia Online de IA para Profesionales Hispanos', 'Los profesionales hispanos saben que la IA les va a afectar pero no saben por dónde empezar. Los cursos de IA son técnicos, en inglés o dan título universitario de 2 años. Necesitan algo práctico ya.', 'Profesionales hispanos 28-45 años, directivos, profesores, periodistas, médicos', 'Enorme demanda en LinkedIn Hispano, 1.000+ búsquedas semanales "curso IA en español para no técnicos"', 'hackernews', 'marketplace', 'medium', '6.000€-20.000€/mes', 90, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Generador de Contratos Legales con IA', 'Los emprendedores en LATAM necesitan contratos pero los abogados cobran caro. Se firman acuerdos verbales que luego generan conflictos. Los templates online son en inglés o de otros países.', 'Emprendedores, freelancers, PYMEs en LATAM', '300+ búsquedas mensuales "contrato para freelancer gratis", múltiples foros de emprendedores hispanos', 'hackernews', 'saas', 'easy', '1.500€-6.000€/mes', 85, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'CRM Simplificado para Coaches y Consultores', 'Los coaches tienen clientes en WhatsApp, Instagram DMs y email. Pierden seguimiento. Salesforce es demasiado complejo. Notion no tiene automatizaciones de cliente.', 'Coaches, consultores, terapeutas, mentores hispanohablantes', '120+ coaches quejándose en Instagram, múltiples grupos de Facebook con el problema', 'twitter', 'saas', 'medium', '2.500€-9.000€/mes', 83, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Herramienta de SEO Local para Negocios Hispanos', 'Los restaurantes y tiendas locales en ciudades hispanas no aparecen en Google. No saben cómo optimizar su ficha de Google Business. Contratar agencia de SEO es prohibitivo.', 'Restaurantes, tiendas, servicios locales en ciudades con comunidad hispana (EEUU y LATAM)', '400+ búsquedas "cómo aparecer en Google Maps gratis", foros de dueños de negocios hispanos en EEUU', 'reddit', 'saas', 'easy', '2.000€-7.000€/mes', 82, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Marketplace de Talento Tech LATAM para Empresas Europeas', 'Empresas europeas buscan developers y diseñadores a costos razonables. El talento LATAM es de calidad pero no sabe cómo acceder al mercado europeo. Los intermediarios cobran el 30%.', 'Developers, diseñadores y marketers LATAM; Startups y PYMEs europeas', 'Múltiples posts en LinkedIn de recruiters europeos, 200+ developers LATAM buscando trabajo remoto en grupos de Facebook', 'twitter', 'marketplace', 'hard', '8.000€-25.000€/mes', 88, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Plataforma de Cursos en Vídeo Cortos para Emprendedores Hispanos', 'Los hispanos quieren aprender marketing digital y ventas pero los cursos son largos, caros y en inglés. TikTok tiene contenido pero disperso. No hay plataforma curada de microaprendizaje.', 'Emprendedores y dueños de negocio hispanohablantes, 25-45 años', '500+ búsquedas "cursos marketing digital en español gratis", éxito de academias como Platzi confirma demanda', 'reddit', 'marketplace', 'hard', '5.000€-20.000€/mes', 80, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Mercado de Servicios Digitales para Negocios Locales', 'Los negocios locales hispanos necesitan logo, web, posts de Instagram. Los diseñadores freelance no tienen visibilidad. Fiverr es en inglés y el proceso es confuso.', 'Pequeños negocios hispanos en LATAM y EEUU, freelancers creativos hispanohablantes', '180+ dueños de negocio en grupos de Facebook buscando "diseñador barato", comunidades de freelancers hispanos activas', 'reddit', 'marketplace', 'medium', '3.000€-10.000€/mes', 77, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Gestor de Redes Sociales con IA para PYMEs', 'Las PYMEs saben que deben publicar en Instagram y TikTok pero no tienen tiempo ni ideas. Contratar community manager cuesta 800€/mes. Herramientas como Buffer son en inglés.', 'PYMEs, restaurantes, tiendas, servicios; dueños que gestionan solos sus redes', '250+ búsquedas "publicar automático instagram gratis", 90+ posts en grupos de PYMEs sobre este problema', 'twitter', 'tool', 'medium', '2.000€-8.000€/mes', 87, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Generador de Presupuestos Automáticos para Servicios', 'Fontaneros, electricistas, pintores pasan tiempo haciendo presupuestos a mano. Algunos ni saben cuánto cobrar. No hay herramienta simple en español para el sector servicios.', 'Autónomos de oficios: fontaneros, electricistas, carpinteros, pintores en España', '100+ búsquedas "plantilla presupuesto fontanero Word", foros de gremios con el problema recurrente', 'hackernews', 'tool', 'easy', '1.000€-4.000€/mes', 79, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Validador de Ideas de Negocio con Research Automático', 'Los emprendedores hispanos tienen ideas pero no saben si hay demanda. Hacen encuestas a amigos (sesgo enorme). No tienen acceso a datos de mercado ni saben interpretar Google Trends.', 'Emprendedores early-stage en LATAM y España, estudiantes de negocios', 'Alta demanda en comunidades como Startup Grind LATAM, 300+ posts "cómo validar mi idea de negocio"', 'hackernews', 'tool', 'medium', '2.500€-8.000€/mes', 86, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Tracker de Gastos con Voz para Autónomos', 'Los autónomos olvidan apuntar gastos deducibles. La app del banco no categoriza correctamente. Hablar con el gestor una vez al año para recordar gastos es una pesadilla.', 'Autónomos y freelancers en España, especialmente en movilidad', '170+ posts en r/autónomos sobre problemas fiscales, múltiples quejas en foros de gestores', 'reddit', 'tool', 'easy', '1.500€-5.000€/mes', 81, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Tienda Online en 24h para Artesanos Hispanos', 'Los artesanos y productores locales de LATAM venden solo en ferias o Instagram DMs. No saben crear una tienda online. Shopify es en inglés y caro para mercados emergentes.', 'Artesanos, productores locales, tiendas de barrio en LATAM y España', '400+ búsquedas "cómo vender por internet sin saber programar", grupos de Facebook de artesanos muy activos', 'twitter', 'saas', 'medium', '2.000€-7.000€/mes', 78, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Comparador de Precios para Proveedores de Restaurantes', 'Los restaurantes compran a 3-5 proveedores distintos y no comparan precios. Pierden entre 500€-2.000€/mes en sobrecostes. No hay plataforma para comparar precios de mayoristas en tiempo real.', 'Restaurantes, bares y hoteles en España y ciudades principales de LATAM', '60+ dueños de restaurante mencionando el problema en grupos de hostelería, mercado validado con demanda clara', 'reddit', 'marketplace', 'hard', '5.000€-18.000€/mes', 76, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'App de Ahorro Automático para Millennials Hispanos', 'Los millennials hispanos saben que deben ahorrar pero no lo hacen. Las apps de ahorro son aburridas y genéricas. La educación financiera en español es escasa o condescendiente.', 'Millennials hispanohablantes, 22-35 años, usuarios de smartphone', '600+ posts en Twitter sobre "no llego a fin de mes", demanda enorme en TikTok financiero en español', 'twitter', 'saas', 'hard', '4.000€-15.000€/mes', 74, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Cobros Fáciles para Profesionales Independientes', 'Psicólogos, tutores, asesores cobran por transferencia y persiguen clientes morosos. No quieren montar una empresa solo para cobrar bien. Las plataformas de pago cobran mucho o son complicadas.', 'Psicólogos, tutores, nutricionistas, asesores independientes en España y LATAM', '90+ profesionales quejándose de cobros en grupos de LinkedIn, validado con entrevistas a coaches', 'hackernews', 'saas', 'medium', '2.000€-8.000€/mes', 80, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Plataforma de Clases Particulares Online en Español', 'Los estudiantes hispanos buscan profes particulares pero la búsqueda es caótica. Los profesores no tienen forma de gestionar su agenda ni cobrar fácil.', 'Estudiantes hispanos 14-25 años y sus padres; profesores particulares hispanohablantes', '800+ búsquedas "clases particulares online en español", mercado comprobado con Superprof aunque con UX deficiente', 'reddit', 'marketplace', 'medium', '4.000€-14.000€/mes', 82, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'App de Psicología Preventiva para Emprendedores', 'El 70% de los emprendedores reporta ansiedad alta. Los servicios de psicología online son caros o no entienden el mundo del emprendimiento. No hay nada específico para founders en español.', 'Emprendedores y founders hispanohablantes, especialmente en etapas iniciales de alto estrés', '200+ posts en comunidades de startups sobre burnout, validado en varias comunidades de Slack de startups hispanas', 'twitter', 'saas', 'hard', '3.000€-12.000€/mes', 75, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Nutrición Personalizada con IA para Hispanos', 'Los planes de nutrición genéricos no consideran la gastronomía hispana. Los nutricionistas cobran caro y no dan seguimiento diario.', 'Adultos hispanos 25-50 años preocupados por su salud o con necesidades específicas', '500+ búsquedas "dieta para hispanos", comunidades de salud muy activas en Facebook e Instagram', 'twitter', 'saas', 'medium', '3.500€-11.000€/mes', 78, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Agencia IA de Marketing para PYMEs a 299€/mes', 'Las PYMEs no pueden pagar una agencia de marketing (mínimo 1.500€/mes). Hacerlo interno requiere contratar. Las herramientas de IA están en inglés o requieren conocimientos técnicos.', 'PYMEs con 2-20 empleados en España y LATAM con presupuesto de marketing limitado', 'Alta demanda en LinkedIn de dueños de PYME buscando "marketing digital barato que funcione"', 'hackernews', 'saas', 'hard', '10.000€-30.000€/mes', 84, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Asistente de Onboarding de Empleados para PYMEs', 'Las PYMEs contratan personas y el primer día es un caos: documentos dispersos, nadie explica los procesos, el nuevo se pierde.', 'PYMEs en crecimiento, entre 5 y 50 empleados, en España y LATAM', '70+ posts en foros de RRHH sobre onboarding caótico en PYMEs, mercado infra-servido', 'reddit', 'saas', 'medium', '2.000€-7.000€/mes', 73, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Encuentra Piso Compartido entre Profesionales Hispanos', 'Los profesionales hispanos que se mudan a nueva ciudad tienen dificultad para encontrar compañeros compatibles. Idealista y Fotocasa tienen pisos, no comunidades.', 'Profesionales hispanos 23-35 años que se mudan por trabajo o estudios', '1.000+ búsquedas "busco piso compartido con profesionales", grupos de Facebook masivos pero mal organizados', 'reddit', 'marketplace', 'medium', '3.000€-9.000€/mes', 71, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Gestión de Reservas para Casas Rurales y Pequeños Hoteles', 'Las casas rurales y hoteles boutique en España tienen reservas en Booking, Airbnb, WhatsApp y llamadas. Gestionarlo es un caos y las comisiones de las plataformas son altísimas.', 'Propietarios de casas rurales, hoteles boutique, apartamentos turísticos en España', '100+ propietarios quejándose de comisiones en grupos de Facebook, demanda real con dinero que pagar', 'hackernews', 'saas', 'medium', '2.500€-9.000€/mes', 77, 'new', true, NOW(), NOW()),
    (gen_random_uuid(), 'Cumplimiento RGPD/LOPD Automatizado para PYMEs', 'Las PYMEs deben cumplir el RGPD pero no saben cómo. Contratar abogado de datos cuesta 2.000€+. Las multas son altas. No hay herramienta asequible que lo simplifique.', 'PYMEs en España y Europa con presencia digital, especialmente ecommerce y servicios online', '200+ búsquedas "como cumplir RGPD PYME sin contratar abogado", foros de ecommerce muy activos con dudas legales', 'hackernews', 'tool', 'medium', '2.000€-8.000€/mes', 83, 'new', true, NOW(), NOW());

    RAISE NOTICE 'Seed: 25 ideas insertadas en discovered_ideas';
  ELSE
    RAISE NOTICE 'Seed: discovered_ideas ya tiene datos, saltando seed';
  END IF;
END $$;
